insert into casting (id, role, credit_order, movies_id, persons_id) values (2, 'Construction Foreman', 4, 17, 38);
insert into casting (id, role, credit_order, movies_id, persons_id) values (3, 'Construction Foreman', 4, 12, 47);
insert into casting (id, role, credit_order, movies_id, persons_id) values (4, 'Subcontractor', 3, 11, 41);
insert into casting (id, role, credit_order, movies_id, persons_id) values (1, 'Architect', 2, 8, 44);
insert into casting (id, role, credit_order, movies_id, persons_id) values (5, 'Engineer', 1, 2, 6);
insert into casting (id, role, credit_order, movies_id, persons_id) values (6, 'Engineer', 3, 4, 29);
insert into casting (id, role, credit_order, movies_id, persons_id) values (7, 'Surveyor', 3, 16, 42);
insert into casting (id, role, credit_order, movies_id, persons_id) values (8, 'Surveyor', 1, 10, 48);
insert into casting (id, role, credit_order, movies_id, persons_id) values (9, 'Subcontractor', 5, 10, 46);
insert into casting (id, role, credit_order, movies_id, persons_id) values (10, 'Construction Foreman', 3, 19, 32);
insert into casting (id, role, credit_order, movies_id, persons_id) values (11, 'Electrician', 5, 20, 46);
insert into casting (id, role, credit_order, movies_id, persons_id) values (12, 'Project Manager', 3, 19, 19);
insert into casting (id, role, credit_order, movies_id, persons_id) values (13, 'Surveyor', 4, 12, 28);
insert into casting (id, role, credit_order, movies_id, persons_id) values (14, 'Architect', 5, 13, 6);
insert into casting (id, role, credit_order, movies_id, persons_id) values (15, 'Project Manager', 2, 12, 46);
insert into casting (id, role, credit_order, movies_id, persons_id) values (16, 'Engineer', 2, 8, 2);
insert into casting (id, role, credit_order, movies_id, persons_id) values (17, 'Engineer', 4, 5, 45);
insert into casting (id, role, credit_order, movies_id, persons_id) values (18, 'Subcontractor', 2, 15, 35);
insert into casting (id, role, credit_order, movies_id, persons_id) values (19, 'Supervisor', 5, 3, 32);
insert into casting (id, role, credit_order, movies_id, persons_id) values (20, 'Supervisor', 5, 15, 1);
insert into casting (id, role, credit_order, movies_id, persons_id) values (21, 'Construction Manager', 1, 19, 27);
insert into casting (id, role, credit_order, movies_id, persons_id) values (22, 'Estimator', 5, 7, 29);
insert into casting (id, role, credit_order, movies_id, persons_id) values (23, 'Electrician', 5, 2, 31);
insert into casting (id, role, credit_order, movies_id, persons_id) values (24, 'Supervisor', 4, 13, 7);
insert into casting (id, role, credit_order, movies_id, persons_id) values (25, 'Construction Expeditor', 5, 2, 17);
insert into casting (id, role, credit_order, movies_id, persons_id) values (26, 'Subcontractor', 3, 10, 40);
insert into casting (id, role, credit_order, movies_id, persons_id) values (27, 'Electrician', 5, 14, 2);
insert into casting (id, role, credit_order, movies_id, persons_id) values (28, 'Construction Manager', 4, 6, 5);
insert into casting (id, role, credit_order, movies_id, persons_id) values (29, 'Architect', 2, 14, 1);
insert into casting (id, role, credit_order, movies_id, persons_id) values (30, 'Supervisor', 1, 8, 28);
insert into casting (id, role, credit_order, movies_id, persons_id) values (31, 'Construction Foreman', 1, 6, 33);
insert into casting (id, role, credit_order, movies_id, persons_id) values (32, 'Estimator', 5, 18, 15);
insert into casting (id, role, credit_order, movies_id, persons_id) values (33, 'Surveyor', 1, 9, 30);
insert into casting (id, role, credit_order, movies_id, persons_id) values (34, 'Project Manager', 3, 12, 25);
insert into casting (id, role, credit_order, movies_id, persons_id) values (35, 'Engineer', 3, 7, 47);
insert into casting (id, role, credit_order, movies_id, persons_id) values (36, 'Engineer', 2, 13, 36);
insert into casting (id, role, credit_order, movies_id, persons_id) values (37, 'Estimator', 5, 4, 9);
insert into casting (id, role, credit_order, movies_id, persons_id) values (38, 'Electrician', 3, 2, 35);
insert into casting (id, role, credit_order, movies_id, persons_id) values (39, 'Engineer', 2, 15, 49);
insert into casting (id, role, credit_order, movies_id, persons_id) values (40, 'Estimator', 1, 7, 31);
insert into casting (id, role, credit_order, movies_id, persons_id) values (41, 'Electrician', 4, 6, 48);
insert into casting (id, role, credit_order, movies_id, persons_id) values (42, 'Construction Manager', 4, 5, 47);
insert into casting (id, role, credit_order, movies_id, persons_id) values (43, 'Subcontractor', 5, 13, 38);
insert into casting (id, role, credit_order, movies_id, persons_id) values (44, 'Architect', 5, 8, 5);
insert into casting (id, role, credit_order, movies_id, persons_id) values (45, 'Construction Manager', 2, 5, 28);
insert into casting (id, role, credit_order, movies_id, persons_id) values (46, 'Construction Foreman', 3, 20, 31);
insert into casting (id, role, credit_order, movies_id, persons_id) values (47, 'Construction Foreman', 3, 2, 14);
insert into casting (id, role, credit_order, movies_id, persons_id) values (48, 'Construction Worker', 3, 5, 24);
insert into casting (id, role, credit_order, movies_id, persons_id) values (49, 'Construction Worker', 2, 11, 14);
insert into casting (id, role, credit_order, movies_id, persons_id) values (50, 'Surveyor', 2, 10, 27);
